version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:14.0
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: password
    #   POSTGRES_DB: postgres
    #   TZ: 'Asia/Tokyo'
    env_file:
      - docker.env
    ports:
      - 54321:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
#   pgadmin:
#     links:
#       - postgres:postgres
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     ports:
#       - "8080:80"
#     volumes:
#       - ./pgadmin-data:/var/lib/pgadmin
#     env_file:
#       - docker.env
#     networks:
#       - postgres

# networks:
#   postgres:
#     driver: bridge